import NavMenu from "../../components/NavMenu";
import Progress from "../../components/Progress";
import "./globals.css";

export const metadata = {
  title: "Sajal's Blog",
  description: "Generated by create next.js & react.js app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <div className="w-3/6 m-auto">
          <NavMenu />
          {children}

          <Progress />
        </div>
      </body>
    </html>
  );
}
